---
title: "EDA"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
research_data <- read.csv("C:/Users/Ruhani R/Downloads/projectdata.csv")
```

Y is economic inequality

```{r}
library(ggplot2)
library(tidyverse)
research_data <- as_tibble(research_data)

research_data_reshaped <- research_data %>%
  pivot_longer(cols = c(X2019.FSI, CPI.score.2019, Inequality.in.Education..2019.),
               names_to = "variable",
               values_to = "value")


ggplot(research_data_reshaped, aes(x = value, y = Inequality.in.income..2019.
)) +
  geom_point(alpha = 0.6) +
  facet_wrap(~ variable, scales = "free_x", ncol = 2,
             labeller = labeller(variable = c(
               "X2019.FSI" = "Political Stability Score",
               "CPI.score.2019" = "Corruption Perception Score",
               "Inequality.in.Education..2019." = "Inequality in Education Score"))) + 
  labs(title = "Income Inequality Scores Vs Other Scores", y = "Income Inequality Score", x = "Score Value")
```

```{r}
research_data <- read.csv("C:/Users/Ruhani R/Downloads/projectdata.csv")
research_data_model = lm(Inequality.in.income..2019.~X2019.FSI + CPI.score.2019 + Inequality.in.Education..2019., data= research_data)

qqnorm(research_data_model$residuals)
qqline(research_data_model$residuals)


```

```{r}
plot(research_data_model, which = 1)
```
